# Generated by Django 5.1.4 on 2026-09-18 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cakes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('reel', 'Instagram Reel')], default='image', max_length=20)),
                ('category', models.CharField(choices=[('Cakes', 'Cakes'), ('Celebrations', 'Celebrations'), ('Videos', 'Videos')], default='Cakes', max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='gallery/')),
                ('image_url', models.URLField(blank=True, help_text='Direct URL to external image or uploaded file path')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='gallery/thumbnails/')),
                ('instagram_url', models.URLField(blank=True)),
                ('title', models.CharField(blank=True, max_length=160)),
                ('published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cake', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media', to='cakes.cake')),
            ],
            options={
                'verbose_name_plural': 'Media items',
                'ordering': ['-created_at'],
            },
        ),
    ]
