# Generated by Django 5.1.4 on 2026-09-18 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='cake',
        ),
        migrations.RemoveField(
            model_name='media',
            name='image_url',
        ),
    ]
