# Generated by Django 5.1.4 on 2026-09-18 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cakes', '0002_remove_cake_category_alter_cake_id_delete_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake',
            name='price',
        ),
    ]
